#!/usr/bin/env python
# -*- mode: Python; coding: latin-1 -*-
# Time-stamp: "2013-05-21 14:16:04 sb"

#  file       SConscript
#  copyright  (c) Sebastian Blatt 2013

# environment variables:
#   LIBPATH, LIBS, ASFLAGS, LINKFLAGS, CPPFLAGS, CPPPATH, CCFLAGS

Import('env')

env.Program('agilent33410A',
            ['agilent33410A.cc'
            ],
    LIBS = ['master'])

# SConscript ends here
