#!/usr/bin/env python
# -*- mode: Python; coding: latin-1 -*-
# Time-stamp: "2014-07-16 10:14:07 sb"

#  file       SConscript
#  copyright  (c) Sebastian Blatt 2013, 2014

# environment variables:
#   LIBPATH, LIBS, ASFLAGS, LINKFLAGS, CPPFLAGS, CPPPATH, CCFLAGS

Import('env')

env.Program('keithley2701',
            ['keithley2701.cc'
            ],
    LIBS = ['master'])

# SConscript ends here
