#!/usr/bin/env python
# -*- mode: Python; coding: latin-1 -*-
# Time-stamp: "2013-08-28 17:29:24 sb"

#  file       SConscript
#  copyright  (c) Sebastian Blatt 2013

# environment variables:
#   LIBPATH, LIBS, ASFLAGS, LINKFLAGS, CPPFLAGS, CPPPATH, CCFLAGS

Import('env')

env.Program('afg3102c',
            ['afg3102c.cc'
            ],
    LIBS = ['master'])

# SConscript ends here
