#!/usr/bin/env python
# -*- mode: Python; coding: latin-1 -*-
# Time-stamp: "2013-05-17 19:33:06 sb"

#  file       SConscript
#  copyright  (c) Sebastian Blatt 2013

# environment variables:
#   LIBPATH, LIBS, ASFLAGS, LINKFLAGS, CPPFLAGS, CPPPATH, CCFLAGS

Import('env')

env.StaticLibrary('master',
                  ['CommandLine.cc',
                   'Representable.cc',
                   'StringVector.cc',
                   'Visa.cc'
                   ])

# SConscript ends here
