#!/usr/bin/env python
# -*- mode: Python; coding: latin-1 -*-
# Time-stamp: "2013-05-17 21:15:10 sb"

#  file       SConscript
#  copyright  (c) Sebastian Blatt 2013

# environment variables:
#   LIBPATH, LIBS, ASFLAGS, LINKFLAGS, CPPFLAGS, CPPPATH, CCFLAGS

Import('env')

env.Program('sr760',
            ['sr760.cc'
            ],
            LIBS = ['master']
    )

# SConscript ends here
